### ISSUE TITLE
Javac compilation error messages are lost when using 'btracec'

### ISSUE THREAD

**Issue by odd2008** [btraceio/btrace#215]
D:\btrace-bin-1.3.5\custom>btracec ThreadSleep.java
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Compilation errors in ThreadSleep.java; can''t run verifier reliably

        at com.sun.tools.javac.main.Main.compile(Main.java:475)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
        at com.sun.btrace.compiler.Compiler.compile(Compiler.java:265)
        at com.sun.btrace.compiler.Compiler.compile(Compiler.java:219)
        at com.sun.btrace.compiler.Compiler.compile(Compiler.java:211)
        at com.sun.btrace.compiler.Compiler.main(Compiler.java:154)
Caused by: java.lang.RuntimeException: Compilation errors in ThreadSleep.java; can't run verifier reliably
        at com.sun.btrace.compiler.Verifier.finished(Verifier.java:106)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:641)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1259)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1218)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:870)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        ... 5 more`

My ThreadSleep.java

 /*

  BTrace Script Template */

 import  com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

@BTrace
public class TracingScript {
	/// @OnMethod annotation tells where to probe.
    // In this example, we are interested in entry 
    // into the Thread.start() method. 
    @OnMethod(
        clazz="java.lang.Thread",
        method="sleep"
    )
    public static void func() {
        // println is defined in BTraceUtils
        // you can only call the static methods of BTraceUtils
        println("about to start a thread!");
    }
}`

My java is jdk1.7.0_80 and 32 bit

**Comment by jbachorik** [comment]
Your class is  __TracingScript__ but it is in file __ThreadSleep.java__
'javac' is expecting __ThreadSleep.java__ containing the __ThreadSleep__ class. Unable to find it, it fails.

**Comment by odd2008** [comment]
thank you.
Sorry my English is very poor.
at 1.2.5 version will tell me public class must be in ThreadSleep.java.
why 1.3.5  only tell me have a exception.

**Comment by jbachorik** [comment]
I see. So the problem is missing javac error messages.
