### ISSUE TITLE
Reinject probe does not work

### ISSUE THREAD

**Issue by TimKack** [btraceio/btrace#220]
When you try to inject the probe a second time __without code change__ a VerifierException is thrown
### Steps to replicate
1. Inject safe code with `btrace <pid> Example.probe`
2. Hit CTRL-C and choose exit
3. repeate step 1

### Error observed
```
com.sun.btrace.VerifierException: side-effects to probed program are not allowed
 at com.sun.btrace.runtime.Verifier.reportError(Verifier.java:204)
 at com.sun.btrace.runtime.Verifier.reportError(Verifier.java:196)
 at com.sun.btrace.runtime.MethodVerifier.visitFieldInsn(MethodVerifier.java:120)
 at com.sun.btrace.org.objectweb.asm.ClassReader.a(Unknown Source)
 at com.sun.btrace.org.objectweb.asm.ClassReader.b(Unknown Source)
 at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
 at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
 at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:385)
 at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:372)
 at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:91)
 at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
 at com.sun.btrace.agent.Client.verifyAndLoad(Client.java:340)
 at com.sun.btrace.agent.Client.loadClass(Client.java:209)
 at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:63)
 at com.sun.btrace.agent.Main.startServer(Main.java:471)
 at com.sun.btrace.agent.Main.access$000(Main.java:58)
 at com.sun.btrace.agent.Main$2.run(Main.java:119)
 at java.lang.Thread.run(Thread.java:745)
```

**Comment by jbachorik** [comment]
Could you share the probe code and BTrace version?
Using AllMethods.java from the samples collection against BTrace 1.3.6 does not reproduce the problem.

**Comment by TimKack** [comment]
Thank you for looking into this! Maybe it is just me not understanding what is violating the rules.
Some comments to the code:
m_action is a string
m_nameValuePairs is a java.util.Properties object declared as 
```
  private String m_action;
  private Properties m_nameValuePairs = new Properties();
```

[RemoteAdminServletStats.java.zip](https://github.com/btraceio/btrace/files/240578/RemoteAdminServletStats.java.zip)

**Comment by jbachorik** [comment]
Thank you for providing the details. Indeed, using `new Properties()` in your tracing code should throw verifier error - one of the limits imposed by BTrace is that you can not create new instances directly.

The problem is that the on repeated re-deploy one part of the BTrace probe that is loaded is renamed to prevent name clashes (classes loaded by bootstrap class loader will not get unloaded) and the verifier didn't take this into account after the latest changes in the internal probe representation code.

Fix is trivial and I will add redeploy scenario to the set of functional tests to capture similar problems early.
