### ISSUE TITLE
BTraceUtils.field may cause class not found

### ISSUE THREAD

**Issue by ymmihw** [btraceio/btrace#227]
Trace script

```
    private static Field fdField = BTraceUtils.field("helloworld.Student", "id"); //2

    @OnMethod(clazz = "helloworld.HelloWorld", method = "add")
    public static void onAdd(Student num) {
        BTraceUtils.println(BTraceUtils.str(num)); // 1
        BTraceUtils.printFields(BTraceUtils.get(fdField, num));//2
    }
```
there is an Error when use //2
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: helloworld/Student
	at com.sun.btrace.BTraceUtils.translate(BTraceUtils.java:6872)
	at com.sun.btrace.BTraceUtils.access$300(BTraceUtils.java:62)
	at com.sun.btrace.BTraceUtils$Reflective.classForName(BTraceUtils.java:5357)
	at com.sun.btrace.BTraceUtils.classForName(BTraceUtils.java:479)
	at com.sun.btrace.BTraceUtils.field(BTraceUtils.java:634)
	at helloworld.TracingScript.<clinit>(Unknown Source)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.sun.btrace.BTraceRuntime.defineClassImpl(BTraceRuntime.java:2417)
	at com.sun.btrace.BTraceRuntime.defineClass(BTraceRuntime.java:527)
	at com.sun.btrace.runtime.BTraceProbe.defineClass(BTraceProbe.java:437)
	at com.sun.btrace.runtime.BTraceProbe.register(BTraceProbe.java:212)
	at com.sun.btrace.agent.Client.loadClass(Client.java:247)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:63)
	at com.sun.btrace.agent.Main.startServer(Main.java:486)
	at com.sun.btrace.agent.Main.access$000(Main.java:58)
	at com.sun.btrace.agent.Main$2.run(Main.java:119)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: helloworld/Student
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.btrace.BTraceUtils$Reflective.classForName(BTraceUtils.java:5355)
	... 14 more
```

when only use //1，the script run perfectly. 
so i think the classpath is not wrong.

**Comment by jbachorik** [comment]
The probe fields are resolved in the context of the bootstrap class path - meaning that any custom classes will not be visible. Just put the field() call directly to the probe handler.

**Comment by ymmihw** [comment]
thank u.
the following code works
```
@OnMethod(clazz = "helloworld.HelloWorld", method = "add")
public static void onAdd(Student student) {
    printFields(get(field("helloworld.Student", "id"), student));
}
```
