### ISSUE TITLE
AllCalls1Sampled.java cause the target process to throw NullPointerException

### ISSUE THREAD

**Issue by ymmihw** [btraceio/btrace#228]
BTrace v.1.3.7 (20160509)

code to trace

```
public class AllCalls1Target {

    public static void add() {
        System.out.println(1);
        Math.abs(2.1);
    }
}
```
when i run the AllCalls1Sampled.java, the target process throws NullPointerException。
```
Exception in thread "Thread-0" java.lang.NullPointerException
	at com.sun.btrace.instr.MethodTracker.updateEndTs(MethodTracker.java:219)
	at btrace.helloworld.target.AllCalls1Target.add(AllCalls1Target.java:6)
	at btrace.helloworld.target.Main$1.run(Main.java:18)
```

**Comment by jbachorik** [comment]
Fixed by https://github.com/btraceio/btrace/commit/eb83334e28790c273d5744cd473b43d021293e2b

Thanks for reporting!

**Comment by jbachorik** [comment]
Build [available](https://bintray.com/btraceio/snapshots/btrace-bin/SNAPSHOT/view#files)
