### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when connecting to JVM

### ISSUE THREAD

**Issue by petercipov** [btraceio/btrace#234]
Step:

 ./btrace 73003  Lags.java

causes following error

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.sun.btrace.org.objectweb.asm.Type.a(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.Type.getType(Unknown Source)
	at com.sun.btrace.runtime.StackTrackingMethodVisitor.<init>(StackTrackingMethodVisitor.java:419)
	at com.sun.btrace.runtime.MethodVerifier.<init>(MethodVerifier.java:85)
	at com.sun.btrace.runtime.BTraceProbe.visitMethod(BTraceProbe.java:118)
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.visitMethod(Unknown Source)
	at com.sun.btrace.runtime.Verifier.visitMethod(Verifier.java:177)
	at com.sun.btrace.org.objectweb.asm.ClassReader.b(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:385)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:372)
	at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:91)
	at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
	at com.sun.btrace.agent.Client.verifyAndLoad(Client.java:340)
	at com.sun.btrace.agent.Client.loadClass(Client.java:209)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:63)
	at com.sun.btrace.agent.Main.startServer(Main.java:471)
	at com.sun.btrace.agent.Main.access$000(Main.java:58)
	at com.sun.btrace.agent.Main$2.run(Main.java:119)
	at java.lang.Thread.run(Thread.java:745)

Lags.java:
import com.sun.btrace.annotations.*;

@BTrace 
public class Lags {
    
}

environment, mac
./btrace --version
BTrace v.1.3.6 (20160424)
java 1.8.0_72

windows 10
BTrace v.1.3.7 (20160509)
java 1.8.0_60

The strange thing is I have tried btrace from jvisualvm plugin and this worked. I assume that there is an older version in it. I just could not figure out from that cryptic error message what is wrong with it

**Comment by jbachorik** [comment]
So, you are using an empty trace script (without any `@OnMethod` or other BTrace specific elements), correct?

**Comment by petercipov** [comment]
Nope this also reproducible with normal script with multiple @onmethod. It crashed, so I was gradually deleting content from from java file and I have end up with this empty class file.

Probably I have something misconfigured, I have a feeling that I have missed some crucial step while installing. I have downloaded binaries, setup JAVA_HOME to jdk in ENV and run it.

**Comment by jbachorik** [comment]
Hm, interesting. Would you be able to share the code you are trying to trace?

**Comment by petercipov** [comment]
of course.
```java

import com.sun.btrace.AnyType;
import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;
import com.sun.btrace.Profiler;

@BTrace 
public class Lags {
    
    private static final long THRESHOLD = 1 * 1000 * 1000 * 1000; //ns
    
    @TLS static Profiler profiler;
    
    @OnMethod(clazz="org.eclipse.jetty.server.Server", method="handle")
    public static void servlet(@ProbeMethodName(fqn=true) String probeMethod) {
        profiler = Profiling.newProfiler();
    }
    
    @OnMethod(clazz="org.eclipse.jetty.server.Server", method="handle", location=@Location(value=Kind.RETURN))
    public static void servletExit(@ProbeMethodName(fqn=true) String probeMethod, @Duration long d) {
        if (profiler == null) return;
        if (d < THRESHOLD ) {
            print("Request OK - under threshold ");
            println(d);
            return;
        }
        
        println("");
        println("---------------------------------------------------");
        print("Duration ");
        println(d);
        
        Profiling.printSnapshot("OVER THRESHOLD PROFILE", profiler);
        
        println("---------------------------------------------------");
        println("");
        
        profiler = null;
    }
    
    @OnMethod(clazz="/net\\.foo\\.service\\..*/", method="/.*/")
    public static void servicesentry(@ProbeMethodName(fqn=true) String probeMethod) {
        if (profiler == null) return;
        Profiling.recordEntry(profiler, probeMethod);
    }

    @OnMethod(clazz="/net\\.foo\\.service\\..*/", method="/.*/", location=@Location(value=Kind.RETURN))
    public static void servicereturnBack(@ProbeMethodName(fqn=true) String probeMethod, @Duration long duration) {
        if (profiler == null) return;
        Profiling.recordExit(profiler, probeMethod, duration);
    }
}
```

**Comment by jbachorik** [comment]
Hm, could you run BTrace in verbose mode and, possibly, dump the instrumented classes?

`btrace -v -d <path to dump instrumented classes> ...`

**Comment by petercipov** [comment]
I could reproduce the same issue with jvisualvm as host (it has installed also btrace plugin in it)

one console output
$jvisualvm
objc[58384]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
btrace DEBUG: debugMode is true
btrace DEBUG: startupRetransform is true
btrace DEBUG: dumpClasses is true
btrace DEBUG: dumpDir is /Users/petercipov/Downloads/btrace-bin-1.3.6/bin/dump
btrace DEBUG: unsafeMode is false
btrace DEBUG: probe descriptor path is .
btrace DEBUG: stdout is false
btrace DEBUG: starting agent thread
btrace DEBUG: starting server at 2020
btrace DEBUG: waiting for clients
btrace DEBUG: client accepted Socket[addr=/127.0.0.1,port=64598,localport=2020]
btrace DEBUG: got instrument command
btrace DEBUG: loading BTrace class
btrace DEBUG: verifying BTrace class ...
btrace DEBUG: java.lang.ArrayIndexOutOfBoundsException: 4
java.lang.ArrayIndexOutOfBoundsException: 4
	at com.sun.btrace.org.objectweb.asm.Type.a(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.Type.getType(Unknown Source)
	at com.sun.btrace.runtime.StackTrackingMethodVisitor.<init>(StackTrackingMethodVisitor.java:419)
	at com.sun.btrace.runtime.MethodVerifier.<init>(MethodVerifier.java:85)
	at com.sun.btrace.runtime.BTraceProbe.visitMethod(BTraceProbe.java:118)
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.visitMethod(Unknown Source)
	at com.sun.btrace.runtime.Verifier.visitMethod(Verifier.java:177)
	at com.sun.btrace.org.objectweb.asm.ClassReader.b(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:385)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:372)
	at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:91)
	at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
	at com.sun.btrace.agent.Client.verifyAndLoad(Client.java:340)
	at com.sun.btrace.agent.Client.loadClass(Client.java:209)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:63)
	at com.sun.btrace.agent.Main.startServer(Main.java:471)
	at com.sun.btrace.agent.Main.access$000(Main.java:58)
	at com.sun.btrace.agent.Main$2.run(Main.java:119)
	at java.lang.Thread.run(Thread.java:745)
btrace DEBUG: sending error command
btrace DEBUG: java.lang.NullPointerException
java.lang.NullPointerException
	at com.sun.btrace.agent.Client.getClassName(Client.java:301)
	at com.sun.btrace.agent.RemoteClient.onCommand(RemoteClient.java:144)
	at com.sun.btrace.agent.Client.errorExit(Client.java:267)
	at com.sun.btrace.agent.Client.loadClass(Client.java:212)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:63)
	at com.sun.btrace.agent.Main.startServer(Main.java:471)
	at com.sun.btrace.agent.Main.access$000(Main.java:58)
	at com.sun.btrace.agent.Main$2.run(Main.java:119)
	at java.lang.Thread.run(Thread.java:745)
btrace DEBUG: waiting for clients


second console output

$./btrace -v -d /Users/petercipov/Downloads/btrace-bin-1.3.6/bin/dump  58384  Lags.java
-bash: ./btrace: No such file or directory
~/Downloads/btrace-bin-1.3.6/bin/dump $ cd ..
~/Downloads/btrace-bin-1.3.6/bin $ ./btrace -v -d /Users/petercipov/Downloads/btrace-bin-1.3.6/bin/dump  58384  Lags.java
DEBUG: dumpDir is /Users/petercipov/Downloads/btrace-bin-1.3.6/bin/dump
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling Lags.java
DEBUG: compiled Lags.java
DEBUG: attaching to 58384
DEBUG: checking port availability: 2020
DEBUG: attached to 58384
DEBUG: loading /Users/petercipov/Downloads/btrace-bin-1.3.6/build/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,dumpClasses=true,dumpDir=/Users/petercipov/Downloads/btrace-bin-1.3.6/bin/dump,bootClassPath=.,systemClassPath=/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/lib/tools.jar,probeDescPath=.
DEBUG: loaded /Users/petercipov/Downloads/btrace-bin-1.3.6/build/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command
DEBUG: entering into command loop


dump dir [Archive.zip](https://github.com/btraceio/btrace/files/396852/Archive.zip)

**Comment by jbachorik** [comment]
Ok, thanks. Now I should have enough info to investigate.

**Comment by jbachorik** [comment]
Hm, are you sure that you could see this issue also in 1.3.7?
For one, I am not even able to compile the script on 1.3.7 unless I mark it as unsafe. While the verifier should not complain here and an issue will be filed this is not related to the AIOOBE you are seeing.

I tried to reproduce with 1.3.7 and JDK 1.8.0_66 and after allowing unsafe mode I don't see any AIOOBE.

**Comment by jbachorik** [comment]
Ok, I got to that exception. Had to patch BTrace to allow compilation of the posted script in safe mode.

**Comment by jbachorik** [comment]
Please, try to verify the fix with the build from https://bintray.com/btraceio/snapshots/btrace-bin/SNAPSHOT#files
