### ISSUE TITLE
Quantize throws java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gila** [btraceio/btrace#253]
Hi all,

Issue #190 seemed to be fixed however, im still experiencing a problem when using it. Here is my btrace program:

```
@BTrace public class downstack {
    private static Aggregation servletDuration = Aggregations.newAggregation(AggregationFunction.QUANTIZE);
    @OnMethod(
    clazz="com.myclass",
    method="mymethod",
    location=@Location(Kind.RETURN)
    )
        public static void t(@Self Object o, @ProbeClassName String pc, @ProbeMethodName( fqn = false) String pm, @Duration long duration) {
             AggregationKey aggregationKey = Aggregations.newAggregationKey(pm);
             int d = (int) duration/1000;
             println(d);
             Aggregations.addToAggregation(servletDuration, aggregationKey, d);
        }
```

Notice I have the println() there, when running the dummy program this is what I see:

`6560
! ERROR
java.lang.ArrayIndexOutOfBoundsException: 161
	at com.sun.btrace.aggregation.Quantize.add(Quantize.java:66)
	at com.sun.btrace.aggregation.Aggregation.add(Aggregation.java:88)
	at com.sun.btrace.BTraceRuntime.addToAggregation(BTraceRuntime.java:1842)
	at com.sun.btrace.BTraceUtils$Aggregations.addToAggregation(BTraceUtils.java:5058)
	at com.gemini.cloudian.s3.S3Handler.$btrace$downstack$1$t(Unknown Source)
	at com.gemini.cloudian.s3.S3Handler.handle(S3Handler.java:290)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)`

I've compiled the code from origin/release-1.3.

**Comment by jbachorik** [comment]
The quantizer is not handling long values well. Will have to fix that.
