### ISSUE TITLE
Caused by: java.lang.VerifyError: Bad local variable type

### ISSUE THREAD

**Issue by yanfeipeng** [btraceio/btrace#262]
Hello @jbachorik 
when i use btrace 1.3.8.3 for check something in my program, sometimes run well, but sometimes i got such a problem:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.pjfun.socketserver.extension.XtReqListener.doXtReq(XtReqListener.java:29)
        at com.pjfun.socketserver.extension.ExtensionSkeleton.handleCmdRequest(ExtensionSkeleton.java:35)
        at com.baitian.mobileserver.extension.AbstractExtension.handleEvent(AbstractExtension.java:45)
        at com.baitian.mobileserver.extension.ExtensionManager.dispatchEvent(ExtensionManager.java:120)
        at com.baitian.mobileserver.task.CmdTask.execute(CmdTask.java:46)
        at com.baitian.mobileserver.task.CmdTask.execute(CmdTask.java:14)
        at com.baitian.mobileserver.task.RequestTask.doRun(RequestTask.java:19)
        at com.baitian.mobileserver.task.InMsgTask.run(InMsgTask.java:16)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    com/pjfun/ext/zervice/zone/model/ZoneData.replyMsg(JJJLjava/lang/String;Ljava/util/Date;)J @0: aload_1
  Reason:
    Type long (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'com/pjfun/ext/zervice/zone/model/ZoneData', long, long_2nd, long, long_2nd, long, long_2nd, 'java/lang/String', 'java
/util/Date' }
    stack: { }
  Bytecode:
    0x0000000: 2bb8 020b bb00 1759 2ab4 000e 1f21 1605
    0x0000010: 1907 1908 03b7 0055 3a09 2a19 09b7 0056
    0x0000020: 1909 b600 57ad bf                      
  Exception Handler Table:
    bci [0, 38] => handler: 38
  Stackmap Table:
    same_locals_1_stack_item_frame(@38,Object[#519])
        at com.pjfun.ext.zervice.zone.ZoneCache.createZoneData(ZoneCache.java:199)
        at com.pjfun.ext.zervice.zone.ZoneCache.getZoneData(ZoneCache.java:58)
        at com.pjfun.ext.zervice.zone.ZoneHandler.getViewInfo(ZoneHandler.java:104)
        at com.pjfun.ext.zervice.zone.ZoneExtension.openView(ZoneExtension.java:67)
        ... 19 more

Is that something like issue #160

**Comment by jbachorik** [comment]
This will be something different than #160 
If you could reproduce the problem and try running `btrace -d <dump_dir> ...` to get dumps of the instrumented classes so I can check which part is causing bytecode verification error.

**Comment by yanfeipeng** [comment]
the dump classes is here!
[dumpClasses.tar.gz](https://github.com/btraceio/btrace/files/698138/dumpClasses.tar.gz)

**Comment by jbachorik** [comment]
I have all the info now. Thanks for reporting this!

**Comment by yanfeipeng** [comment]
I try to check the dump class to find:
public synchronized void setDead();
    Code:
       0: aload_1
       1: invokestatic  #65                 // Method $btrace$com$sun$btrace$samples$NestedSyncOrLockCheck$onSyncEntry:(Ljava/lang/Object;)V
       4: aload_0
       5: iconst_3
       6: putfield      #5                  // Field status:I
       9: return
      10: athrow
    Exception table:
       from    to  target type
           0    10    10   Class java/lang/Throwable
Is it the reson that when AOP before synchronized method, my AOP function onSyncEntry need  a parameter (Ljava/lang/Object;), but the function setDead() with no parameters, and the code 0:aload_1 put the setDead() first parameter to the stack trigger the error?
Can i rewrite my AOP function onSyncEntry with no parameters to aviod the error?

**Comment by jbachorik** [comment]
Yes, you can rewrite it not to use the parameter. But it should work also with the parameter and I will fix that.

**Comment by yanfeipeng** [comment]
Great! Thanks for reply!
Waiting for the next version!

**Comment by jbachorik** [comment]
The SYNC instrumentation was revamped in #269 
Any chance you might re-check with the current build?
