### ISSUE TITLE
Got java.lang.IllegalArgumentException after starting the btrace

### ISSUE THREAD

**Issue by DeanCZH** [btraceio/btrace#277]
I got below exception after I tried to run the btrace script, I am using jdk1.8.0_91

! ERROR
java.lang.IllegalArgumentException
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
	at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:73)
	at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:84)
	at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
	at com.sun.btrace.agent.Client.load(Client.java:399)
	at com.sun.btrace.agent.Client.loadClass(Client.java:262)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
	at com.sun.btrace.agent.Main.startServer(Main.java:580)
	at com.sun.btrace.agent.Main.access$000(Main.java:60)
	at com.sun.btrace.agent.Main$2.run(Main.java:123)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DeanCZH** [comment]
I import the old jar with on maven repository....
