### ISSUE TITLE
Btrace collects data stored in a database error

### ISSUE THREAD

**Issue by ouyangkongtong** [btraceio/btrace#286]
hi @jbachorik ,

The data collected with Btrace is stored in a database error；

command：
      
1、 btrace command : 
```sh -x ${BTRACE_HOME}/bin/btrace -cp ${BTRACE_HOME}/build/mysql-connector-java-6.0.6.jar -u 33658 ApplicationCollectionTrace.class```

2、btrace script ：

```
static volatile Connection connection = null;
static Object o = new Object();
public static Connection getConnection() throws Exception {
        if (connection == null || connection.isClosed()) {
            synchronized (o) {
                if (connection == null) {
                    String url = "jdbc:mysql://127.0.0.1:3306/test";
                    String userName = "root";
                    String userPassword = "root";
                    try {
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        connection = DriverManager.getConnection(url, userName, userPassword);
                    } catch (Exception e) {
                        println("getConnection:" + e.getCause().toString());
                    }
                }
            }
        }
        return connection;
    }
```

error info:

```! ERROR
java.lang.ExceptionInInitializerError
	at com.mysql.cj.core.Constants.<clinit>(Constants.java:40)
	at com.mysql.cj.core.util.Util.<clinit>(Util.java:59)
	at com.mysql.cj.core.conf.url.ConnectionUrl.processColdFusionAutoConfiguration(ConnectionUrl.java:326)
	at com.mysql.cj.core.conf.url.ConnectionUrl.collectProperties(ConnectionUrl.java:315)
	at com.mysql.cj.core.conf.url.ConnectionUrl.<init>(ConnectionUrl.java:292)
	at com.mysql.cj.core.conf.url.SingleConnectionUrl.<init>(SingleConnectionUrl.java:38)
	at com.mysql.cj.core.conf.url.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:202)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:194)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.alibaba.middleware.rainbow.toa.aas.applicationcollection.ApplicationCollectionTrace.getConnection(Unknown Source)
	at com.alibaba.middleware.rainbow.toa.aas.applicationcollection.ApplicationCollectionTrace.insert(Unknown Source)
	at com.sun.btrace.BTraceRunnable$0.run(Unknown Source)
	at com.sun.btrace.BTraceRuntime$19.run(BTraceRuntime.java:2307)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Can't load resource bundle due to underlying exception java.lang.NullPointerException
	at com.mysql.cj.core.Messages.<clinit>(Messages.java:54)
	... 16 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.mysql.cj.core.LocalizedErrorMessages, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at com.mysql.cj.core.Messages.<clinit>(Messages.java:52)
	... 16 more```

**Comment by jbachorik** [comment]
To start with using DB to store data collected in BTrace script is pretty heavyweight and can lead to many problems - class loading issues, increased memory footprint, unintended class initialization pops into mind immediately.

In this case the `mysql-connector-java-6.0.6.jar` is added to the traced application bootstrap classpath (loaded by the bootstrap classloader) but the resource bundle localization code does not seem to like it very much.

**Comment by jbachorik** [comment]
Closing due no response.
