### ISSUE TITLE
Issue about btrace <pid> xxx.java in windows's CMD!

### ISSUE THREAD

**Issue by lsunwing** [btraceio/btrace#287]
when I execute this command, there is nothing in cmd, press Ctrl + C, always show "Please enter your options:", 
1. exit
2. send an event
3. send a named event
I entered 2, but also nothing show.....

and in console, error bolow:
Exception in thread "Thread-0" java.lang.NoSuchMethodError: com.sun.btrace.BTraceRuntime.init(Lcom/sun/btrace/PerfReader;Lcom/sun/btrace/RunnableGenerator;)V
	at com.sun.btrace.agent.Client.<clinit>(Client.java:94)
	at com.sun.btrace.agent.Main.startServer(Main.java:379)
	at com.sun.btrace.agent.Main.access$0(Main.java:351)
	at com.sun.btrace.agent.Main$3.run(Main.java:166)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jbachorik** [comment]
Please, specify the BTrace version - `btrace --version`

**Comment by jbachorik** [comment]
Any followup?

**Comment by jbachorik** [comment]
Closing due to inactivity. If you are able to provide the requested details, please, feel free to reopen.

**Comment by feelgood3000** [comment]
when i run the script "btrace 1491 AllMethods.class"
my console show follow tips:
Exception in thread "Thread-0" java.lang.NoSuchMethodError: com.sun.btrace.BTraceRuntime.init(Lcom/sun/btrace/PerfReader;Lcom/sun/btrace/RunnableGenerator;)V
	at com.sun.btrace.agent.Client.<clinit>(Client.java:94)
	at com.sun.btrace.agent.Main.startServer(Main.java:379)
	at com.sun.btrace.agent.Main.access$000(Main.java:65)
	at com.sun.btrace.agent.Main$3.run(Main.java:166)
	at java.lang.Thread.run(Thread.java:748)
AllMethods.java
`@BTrace
public class AllMethods {
    @OnMethod(
            clazz = "com.demo.btrace.Demo",
            method = "test",
            location = @Location(Kind.RETURN)
    )
    public static void m(@Return long sum){
        println("test");
    }
}`
Demo.java
`public class Demo {

    public static void main(String[] args){

        Demo demo=new Demo();
        for (int i = 0; i < 1000; i++) {
            try {
                Thread.sleep(1000*5);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            demo.test();
        }
    }

    public static long count=0;


    public long test(){
        count++;
        return count;
    }
}`
