### ISSUE TITLE
Btrace failed in openjdk8 due to SecurityException

### ISSUE THREAD

**Issue by RalphSu** [btraceio/btrace#296]
Hi,

I got below 
`java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.SecurityException: Unsafe
        at sun.misc.Unsafe.getUnsafe(Unsafe.java:90)
        at com.sun.btrace.BTraceRuntime.initUnsafe(BTraceRuntime.java:458)
        at com.sun.btrace.agent.Main.main(Main.java:131)
        at com.sun.btrace.agent.Main.premain(Main.java:86)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed`

The environment is a docker container which use openjdk 8 (/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar) on top of ubuntu 16.04.

Any step to get rid of it? There are couple of suggestion from SO indicates need to change code like: https://stackoverflow.com/questions/13003871/how-do-i-get-the-instance-of-sun-misc-unsafe. Is that make sense?

**Comment by RalphSu** [comment]
i am able to run with -javaagent:path-to-btrace-agent.jar on my mac with hotspot jvm like below.

LM-SHC-16501232:ebay liasu$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by RalphSu** [comment]
btw, i trid to hack the one refered in SO, but failed to build from lastest release yet (gradlew distribution also the ant dist).

**Comment by RalphSu** [comment]
hmm..

It turns out that it's btrace-boot.jar not copied together with btrace-agent.jar when i deploy btrace to container. After i copied them, together, application starts well.  Thanks!

**Comment by RalphSu** [comment]
Close this one as it's not an issue.!
