### ISSUE TITLE
monitored function can not contains Thread.sleep??

### ISSUE THREAD

**Issue by anzhilin** [btraceio/btrace#300]
i'm using btrace v1.3.9 and java v1.8.0_121

Main class:
```
package com.xxx.yyy;

/**
 * Created by an on 11/13/17.
 */
public class MyClass {

    public static void main(String[] args) throws InterruptedException {
        MyClass myClass = new MyClass();
        while(true){
            System.out.println(myClass.fun(111));
        }
    }

    public int fun(Integer val) throws InterruptedException {
        Thread.sleep(1000);
        return val+1;
    }
}
```

btrace script:
```
import com.sun.btrace.annotations.*;  
import static com.sun.btrace.BTraceUtils.*;


@BTrace
public class Collector{
	@OnMethod(clazz = "com.xxx.yyy.MyClass",method="fun",location=@Location(Kind.RETURN))
	public static void handleTrace(@ProbeClassName String name,@ProbeMethodName String method,Integer val){
		println("execute-------");
		println(val);
		println("end--------");
	}
}
```

When i typing ^C in btrace terminal and select 1,MyClass throws NoSuchMethodError exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.xxx.yyy.MyClass.$btrace$Collector$handleTrace(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)V
	at com.xxx.yyy.MyClass.fun(Unknown Source)
	at com.xxx.yyy.MyClass.main(Unknown Source)
```

**Comment by jbachorik** [comment]
This is specific to intercepting a method which is on stack while JVM is exiting.
BTrace performs de-instrumentation upon exit but bytecode for the method on stack will not get replaced - therefore the method will try calling the BTrace handler which just has been removed. I guess the 'fun' method will get inlined and therefore it appears as a part of the `main` method loop (but haven't verified this assumption with JITWatch - the symptoms would correspond though)
