### ISSUE TITLE
failed to trace trace and got "Agent JAR loaded but agent failed to initialize"

### ISSUE THREAD

**Issue by xiezhenye** [btraceio/btrace#303]
I'm using btrace 1.3.10 to trace elasticsearch (5.1.2). 
OS: CentOS release 6.9, 2.6.32-696.1.1.el6.x86_64

run `sudo -u app -i /tmp/btrace/bin/btrace -v 24929 /tmp/T.java` (same user app as running elasticsearch)

    DEBUG: assuming default port 2020
    DEBUG: assuming default classpath '.'
    DEBUG: compiling /tmp/T.java
    DEBUG: compiled /tmp/T.java
    DEBUG: attaching to 24929
    DEBUG: checking port availability: 2020
    DEBUG: attached to 24929
    DEBUG: loading /tmp/btrace/build/btrace-agent.jar
    DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=/opt/java/jre/../lib/tools.jar,probeDescPath=.
    Agent JAR loaded but agent failed to initialize

T.java:

    package samples;

    import com.sun.btrace.annotations.*;
    import static com.sun.btrace.BTraceUtils.*;

    @BTrace
    public class T {
        @OnMethod(
            clazz="java.nio.file.Path",
            method="toRealPath"
        )
        public static void m(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
            print(Strings.strcat("entered ", probeClass));
            println(Strings.strcat(".", probeMethod));
        }
    }

while trying more times, got 

    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    .....
    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    DEBUG: server not yet available: Connection refused (Connection refused); retrying ...
    Exception in thread "main" java.lang.NullPointerException
        at com.sun.btrace.client.Client.submit(Client.java:369)
        at com.sun.btrace.client.Main.main(Main.java:201)
    DEBUG: sending exit command
    Exception in thread "Thread-0" java.lang.IllegalStateException
        at com.sun.btrace.client.Client.send(Client.java:487)
        at com.sun.btrace.client.Client.sendExit(Client.java:421)
        at com.sun.btrace.client.Main$2.run(Main.java:235)
        at java.lang.Thread.run(Thread.java:745)

**Comment by xiezhenye** [comment]
find an exception in app's log

    java.security.AccessControlException: access denied ("java.util.PropertyPermission" "btrace.port" "write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_111]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_111]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_111]
        at java.lang.System.setProperty(System.java:792) ~[?:1.8.0_111]
        at com.sun.btrace.agent.Main.startServer(Main.java:653) ~[btrace-agent.jar:?]
        at com.sun.btrace.agent.Main.access$000(Main.java:60) ~[btrace-agent.jar:?]
        at com.sun.btrace.agent.Main$2.run(Main.java:126) ~[btrace-agent.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by jbachorik** [comment]
Your application is running with security manager preventing BTrace from performing some operations. You will need to modify the security policy to allow BTrace to do its thing.

**Comment by xiezhenye** [comment]
You are right. After disable SecurityManager, it will ok.
