### ISSUE TITLE
Using v1.3.10 fails with java.lang.VerifyError: StackMapTable error: bad offset

### ISSUE THREAD

**Issue by pibako** [btraceio/btrace#304]
Hi,

I've been trying to learn BTrace to instrument Tomcat to debug production bug I experience but run into some problems with the newest release v1.3.10. The below are steps to reproduce it.

I downloaded a vanilla apache-tomcat-8.0.44.tar.gz from apache and configured two connectors, one nio and the second nio2 in server.xml:
```xml
    <Connector port="8080"
               protocol="org.apache.coyote.http11.Http11Nio2Protocol"
               connectionTimeout="20000"/>

    <Connector port="8088"
               protocol="org.apache.coyote.http11.Http11NioProtocol"
               connectionTimeout="20000"/>
```

Then I wrote a script to trace all invocations of methods in Nio2* tomcat classes:
```java
import com.sun.btrace.annotations.*;
import com.sun.btrace.AnyType;

import static com.sun.btrace.BTraceUtils.*;

@BTrace
public class TomcatPlay {
    @TLS private static String method;

    @OnMethod(
            clazz = "/org\\.apache\\.tomcat\\.util\\.net\\.Nio2.*/",
            method = "/.*/"
    )
    public static void onNio2(
            @ProbeClassName String className,
            @ProbeMethodName String probeMethod,
            AnyType[] args ) {
        println(strcat("Method ", strcat( strcat( className, "::" ), probeMethod )));
        printArray(args);
        jstack();
    }
}
```

When I run it with v1.3.10 and send a sample request to `localhost:8080/foo/aa` it crashes with:
```
pi@mac:~/Desktop/apache-tomcat-8.0.44$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/ bin/catalina.sh run
Using CATALINA_BASE:   /Users/pi/Desktop/apache-tomcat-8.0.44
Using CATALINA_HOME:   /Users/pi/Desktop/apache-tomcat-8.0.44
Using CATALINA_TMPDIR: /Users/pi/Desktop/apache-tomcat-8.0.44/temp
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/
Using CLASSPATH:       /Users/pi/Desktop/apache-tomcat-8.0.44/bin/bootstrap.jar:/Users/pi/Desktop/apache-tomcat-8.0.44/bin/tomcat-juli.jar
04-Dec-2017 19:29:40.483 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.44
04-Dec-2017 19:29:40.485 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 10 2017 17:21:09 UTC
04-Dec-2017 19:29:40.485 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.44.0
04-Dec-2017 19:29:40.485 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.13.1
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_92-b14
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /Users/pi/Desktop/apache-tomcat-8.0.44
04-Dec-2017 19:29:40.486 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /Users/pi/Desktop/apache-tomcat-8.0.44
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/Users/pi/Desktop/apache-tomcat-8.0.44/conf/logging.properties
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/Users/pi/Desktop/apache-tomcat-8.0.44/endorsed
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/Users/pi/Desktop/apache-tomcat-8.0.44
04-Dec-2017 19:29:40.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/Users/pi/Desktop/apache-tomcat-8.0.44
04-Dec-2017 19:29:40.488 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/Users/pi/Desktop/apache-tomcat-8.0.44/temp
04-Dec-2017 19:29:40.488 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /Users/pi/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
04-Dec-2017 19:29:40.610 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio2-8080"]
04-Dec-2017 19:29:40.687 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8088"]
04-Dec-2017 19:29:40.698 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
04-Dec-2017 19:29:40.700 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 527 ms
04-Dec-2017 19:29:40.716 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
04-Dec-2017 19:29:40.717 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.44
04-Dec-2017 19:29:40.733 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/foo-1.0-SNAPSHOT.war
04-Dec-2017 19:29:40.981 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
04-Dec-2017 19:29:41.011 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/foo-1.0-SNAPSHOT.war has finished in 278 ms
04-Dec-2017 19:29:41.012 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/docs
04-Dec-2017 19:29:41.023 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/docs has finished in 11 ms
04-Dec-2017 19:29:41.024 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/manager
04-Dec-2017 19:29:41.054 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/manager has finished in 30 ms
04-Dec-2017 19:29:41.054 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/examples
04-Dec-2017 19:29:41.205 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/examples has finished in 151 ms
04-Dec-2017 19:29:41.205 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/foo
04-Dec-2017 19:29:41.228 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
04-Dec-2017 19:29:41.230 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/foo has finished in 25 ms
04-Dec-2017 19:29:41.230 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/ROOT
04-Dec-2017 19:29:41.243 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/ROOT has finished in 13 ms
04-Dec-2017 19:29:41.243 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/host-manager
04-Dec-2017 19:29:41.258 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /Users/pi/Desktop/apache-tomcat-8.0.44/webapps/host-manager has finished in 14 ms
04-Dec-2017 19:29:41.260 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio2-8080"]
04-Dec-2017 19:29:41.261 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8088"]
04-Dec-2017 19:29:41.263 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 563 ms
objc[99791]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home//bin/java (0x108ef04c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10f2784e0). One of the two will be used. Which one is undefined.
btrace DEBUG: parsed command line arguments
btrace DEBUG: Bootstrap ClassPath: .
btrace WARNING: BTrace bootstrap classpath resource [ .] does not exist
btrace DEBUG: System ClassPath: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar
btrace DEBUG: debugMode is true
btrace DEBUG: dumpClasses is true
btrace DEBUG: dumpDir is /tmp/foo/
btrace DEBUG: probe descriptor path is .
btrace DEBUG: stdout is false
btrace DEBUG: starting agent thread
btrace DEBUG: starting server at 2020
btrace DEBUG: waiting for clients
btrace DEBUG: Agent init took: 8445061ns
btrace DEBUG: client accepted Socket[addr=/127.0.0.1,port=62547,localport=2020]
btrace DEBUG: got instrument command
btrace DEBUG: loading BTrace class
btrace DEBUG: verifying BTrace class ...
btrace DEBUG: BTrace class TomcatPlay verified
btrace DEBUG: preprocessing BTrace class TomcatPlay ...
btrace DEBUG: ... preprocessed
btrace DEBUG: loaded 'TomcatPlay' successfully
btrace DEBUG: creating BTraceRuntime instance for TomcatPlay
btrace DEBUG: created BTraceRuntime instance for TomcatPlay
btrace DEBUG: sending Okay command
btrace DEBUG: client TomcatPlay: got com.sun.btrace.comm.OkayCommand@507993b6
btrace DEBUG: about to defineClass TomcatPlay
btrace DEBUG: defineClass succeeded for TomcatPlay
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/agent/RemoteClient$1
btrace DEBUG: starting client command handler thread
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/agent/Main$3
btrace DEBUG: skipping transform for BTrace class java/lang/instrument/UnmodifiableClassException
btrace DEBUG: new Client created com.sun.btrace.agent.RemoteClient@9e5a749
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassCache$Singleton
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$ClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$JavaClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$BaseClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$InternalClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/BTraceClassReader$BailoutException
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Endpoint$3 added
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Endpoint$2 added
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper added
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Channel added
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Endpoint$Acceptor added
btrace DEBUG: candidate class org.apache.tomcat.util.net.Nio2Endpoint added
btrace DEBUG: client TomcatPlay: got com.sun.btrace.comm.RetransformationStartNotification@b03db62
btrace DEBUG: calling retransformClasses (6 classes to be retransformed)
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Endpoint$3
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint$3
btrace DEBUG: verification error: org.apache.tomcat.util.net.Nio2Endpoint$3
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Endpoint$2
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint$2
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper
btrace DEBUG: verification error: org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Channel
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Channel
btrace DEBUG: verification error: org.apache.tomcat.util.net.Nio2Channel
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Endpoint$Acceptor
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint$Acceptor
btrace DEBUG: Attempting to retransform class: org.apache.tomcat.util.net.Nio2Endpoint
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint
btrace DEBUG: verification error: org.apache.tomcat.util.net.Nio2Endpoint
btrace DEBUG: waiting for clients
btrace DEBUG: client TomcatPlay: got com.sun.btrace.comm.OkayCommand@16e71a69
btrace DEBUG: transformed class org.apache.tomcat.util.net.Nio2Endpoint$NioBufferHandler
04-Dec-2017 19:30:11.140 SEVERE [http-nio2-8080-Acceptor-0] org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions
 java.lang.VerifyError: StackMapTable error: bad offset
Exception Details:
  Location:
    org/apache/tomcat/util/net/Nio2Endpoint$NioBufferHandler.<init>(IIZ)V @0: aload_0
  Reason:
    Invalid stackmap specification.
  Current Frame:
    bci: @154
    flags: { }
    locals: { 'org/apache/tomcat/util/net/Nio2Endpoint$NioBufferHandler', integer, integer, integer }
    stack: { }
  Bytecode:
    0x0000000: 2ab7 0001 1235 1236 06bd 0007 5903 1bb8
    0x0000010: 003c 5359 041c b800 3c53 5905 1db8 0041
    0x0000020: 53b8 0045 2a01 b500 022a 01b5 0003 1d99
    0x0000030: 0016 2a1b b800 04b5 0002 2a1c b800 04b5
    0x0000040: 0003 a700 132a 1bb8 0005 b500 022a 1cb8
    0x0000050: 0005 b500 03b1
  Stackmap Table:
    full_frame(@69,{Object[#6],Integer,Integer,Integer},{})
    same_frame_extended(@154)

	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:520)
	at org.apache.tomcat.util.net.Nio2Endpoint$Acceptor.run(Nio2Endpoint.java:737)
	at java.lang.Thread.run(Thread.java:745)

04-Dec-2017 19:30:11.145 SEVERE [http-nio2-8080-Acceptor-0] org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions
 java.lang.VerifyError: StackMapTable error: bad offset
Exception Details:
  Location:
    org/apache/tomcat/util/net/Nio2Endpoint$NioBufferHandler.<init>(IIZ)V @0: aload_0
  Reason:
    Invalid stackmap specification.
  Current Frame:
    bci: @154
    flags: { }
    locals: { 'org/apache/tomcat/util/net/Nio2Endpoint$NioBufferHandler', integer, integer, integer }
    stack: { }
  Bytecode:
    0x0000000: 2ab7 0001 1235 1236 06bd 0007 5903 1bb8
    0x0000010: 003c 5359 041c b800 3c53 5905 1db8 0041
    0x0000020: 53b8 0045 2a01 b500 022a 01b5 0003 1d99
    0x0000030: 0016 2a1b b800 04b5 0002 2a1c b800 04b5
    0x0000040: 0003 a700 132a 1bb8 0005 b500 022a 1cb8
    0x0000050: 0005 b500 03b1
  Stackmap Table:
    full_frame(@69,{Object[#6],Integer,Integer,Integer},{})
    same_frame_extended(@154)

	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:520)
	at org.apache.tomcat.util.net.Nio2Endpoint$Acceptor.run(Nio2Endpoint.java:737)
	at java.lang.Thread.run(Thread.java:745)
```

This is how I attach btrace to java process:
```
pi@mac:~/Desktop/btrace-vm$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/ ./bin/btrace -v `jps -v | grep catalina | awk '{ print $1 }'` ~/code/btrace/dataxu.btrace/src/main/java/TomcatPlay.java
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling /Users/pi/code/btrace/dataxu.btrace/src/main/java/TomcatPlay.java
DEBUG: compiled /Users/pi/code/btrace/dataxu.btrace/src/main/java/TomcatPlay.java
DEBUG: attaching to 22520
DEBUG: checking port availability: 2020
DEBUG: attached to 22520
DEBUG: loading /Users/pi/Desktop/btrace-vm/build/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar,probeDescPath=.
DEBUG: loaded /Users/pi/Desktop/btrace-vm/build/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command
DEBUG: entering into command loop
DEBUG: received com.sun.btrace.comm.OkayCommand@ed9d034
DEBUG: received com.sun.btrace.comm.RetransformationStartNotification@6121c9d6
DEBUG: received com.sun.btrace.comm.OkayCommand@87f383f
```
The same script seems to work fine when using the v1.3.8.3-1 (either through visualvm or through command line). For reference this is the test app I'm running: https://github.com/pibako/DeadSimpleServlet

BTW, is visualvm btrace workbench plugin closed source? I couldn't find it anywhere and the way I figured the version it uses was... through twitter post https://twitter.com/btraceio/status/796324086012067840.

Please let me know if there is something else I can do to help.

Also noted that the following condition is likely missing a negation:
https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/agent/Main.java#L470

**Comment by jbachorik** [comment]
Thanks for reporting this!
In 1.3.10 BTrace got a complete overhaul of stackmap frame calculation algorithm aimed at improved performance (not recalculating stackmap frames when method has not changed) as well as reliability (default ASM algorithm relies on getting common superclass which is not very reliable in dynamic environments - and in BTrace we do very limited subset of bytecode modification so we can take some shortcuts). Unfortunately, the whole stackmap frame calculation affair is pretty complex and ASM API is not very well suited (or documented) for what I am trying to achieve here - resulting in some leftover bugs. This particular problem was caused by ASM getting thrown off by mixing F_NEW and other frame types in certain cases - usually ASM handles that pretty well and generates the correct final stackframe maps but sometimes it fails and generates bogus offsets. The fix is not to use the shortcut and emit all maps as F_NEW from out code.

**Comment by pibako** [comment]
Fantastic, thanks for fixing this @jbachorik!
