### ISSUE TITLE
Regression: NPE in Preprocessor.loadEventHandlers when trying to attach

### ISSUE THREAD

**Issue by tmohme** [btraceio/btrace#305]
When trying to attach to a running JVM (with btrace >= 1.3.10), I get a NullPointerException like this:

```
$ btrace-bin-1.3.10/bin/btrace 57137 btrace-bin-1.3.10/samples/JdbcQueries.java 
! ERROR
java.lang.NullPointerException
	at com.sun.btrace.runtime.Preprocessor.loadEventHandlers(Preprocessor.java:585)
	at com.sun.btrace.runtime.Preprocessor.initRuntime(Preprocessor.java:508)
	at com.sun.btrace.runtime.Preprocessor.processClinit(Preprocessor.java:500)
	at com.sun.btrace.runtime.Preprocessor.process(Preprocessor.java:205)
	at com.sun.btrace.runtime.BTraceProbeNode.initialize(BTraceProbeNode.java:395)
	at com.sun.btrace.runtime.BTraceProbeNode.initialize(BTraceProbeNode.java:377)
	at com.sun.btrace.runtime.BTraceProbeNode.<init>(BTraceProbeNode.java:74)
	at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:72)
	at com.sun.btrace.agent.Client.load(Client.java:413)
	at com.sun.btrace.agent.Client.loadClass(Client.java:276)
	at com.sun.btrace.agent.Client.loadClass(Client.java:269)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
	at com.sun.btrace.agent.Main.startServer(Main.java:673)
	at com.sun.btrace.agent.Main.access$000(Main.java:60)
	at com.sun.btrace.agent.Main$2.run(Main.java:125)
	at java.lang.Thread.run(Thread.java:748)
```

This works fine with 1.3.9.  
I'm running this on macOS 10.12.6 with oracle JDK8:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by tmohme** [comment]
Hi Jaroslav,

thx for the fast fix.
While I tried to reproduce your steps to fix this, two questions came into my mind:
- How do you debug this? Is it possible to attach a debugger (to the target process) to see what btrace is doing?
-  Now that `EventHandler#getEvent` guarantees a non-null result, do we still need `BTraceRuntime#handleEvent`, line#583?

Best regards,
Thomas

**Comment by jbachorik** [comment]
I either debug the instrumentation tests (it is useful when dealing with bytecode modifications only) or fire an app (eg. AnagramGame from NetBeans sample collection ;) in debug mode and then attach BTrace via `btrace <pid> ...` - you can put breakpoints to BTrace runtime code and they will be properly handled.

As for L583 in `BTraceRuntime` - yes, it is a redundant check. I will probably remove it before completing 1.3.10.2 release.
