### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by moooonk** [btraceio/btrace#333]
Hello @jbachorik
I use btrace-1.3.11 do some check in my project, and found this Exception.
I found my AOP funtion can not attach on some kind of Class with @Location(value=Kind.SYNC_ENTRY).
I don't sure my problem has something to do with this Exception,but I think this Exception is bug.

btrace DEBUG: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.sun.btrace.runtime.InstrumentingMethodVisitor.fromSlotType(InstrumentingMethodVisitor.java:1464)
	at com.sun.btrace.runtime.InstrumentingMethodVisitor.visitVarInsn(InstrumentingMethodVisitor.java:683)
	at com.sun.btrace.org.objectweb.asm.MethodVisitor.visitVarInsn(Unknown Source)
	at com.sun.btrace.util.templates.TemplateExpanderVisitor.visitVarInsn(TemplateExpanderVisitor.java:79)
	at com.sun.btrace.org.objectweb.asm.MethodVisitor.visitVarInsn(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.MethodVisitor.visitVarInsn(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.MethodVisitor.visitVarInsn(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.a(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.b(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.runtime.BTraceClassReader.accept(BTraceClassReader.java:174)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.runtime.BTraceClassReader.accept(BTraceClassReader.java:183)
	at com.sun.btrace.runtime.InstrumentUtils.accept(InstrumentUtils.java:177)
	at com.sun.btrace.runtime.InstrumentUtils.accept(InstrumentUtils.java:171)
	at com.sun.btrace.runtime.BTraceClassWriter.instrument(BTraceClassWriter.java:82)
	at com.sun.btrace.runtime.BTraceTransformer.transform(BTraceTransformer.java:184)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.sun.btrace.agent.Client.retransformLoaded(Client.java:478)
	at com.sun.btrace.agent.Main$3.run(Main.java:692)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jbachorik** [comment]
Could you share the method source causing this problem?
Thanks!

**Comment by moooonk** [comment]
Source here. 
And with my test,this source can run in btrace-1.3.8.3 no Exception.


package com.sun.btrace.samples;

import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

@BTrace(unsafe=true) public class AllMethods {
    @OnMethod(
        clazz="com.bt.pjg.game.backpack.BackpackService",
        method="/.*/",
		location=@Location(value=Kind.SYNC_ENTRY)
    )
    public static void m() {
        print("entered SYNC");
    }
	
	@OnMethod(
        clazz="com.bt.pjg.game.backpack.BackpackService",
        method="/.*/",
		location=@Location(value=Kind.ENTRY)
    )
    public static void m2() {
        print("entered run");
    }
}

**Comment by jbachorik** [comment]
I guess `BackpackService` is a closed source. I will try to figure out the problem from the available data. This is all due to stackframe maps in bytcode - it is very complex area without extensive documentation unfortunately :( Thanks for patience!

**Comment by moooonk** [comment]
BackpackService is My company project source.I'm sorry.It's not convenient for me to share the detail source.
But I can share the source structure.I hope it will help you。

public class BackpackService {
	private static final BackpackService instance = new BackpackService();

	private BackpackManger manager;

	private BackpackService() {
		
	}

	public static BackpackService instance() {
		return instance;
	}

	public void init() {
		
	}

	public CacheMap<ItemBase> getItemMap(long userId) {
		
	}

	public List<ItemBase> getItemList(long userId) {
		
	}

	public ItemBase getItemById(long userId, int itemId) {
		
	}
	
	public int getItemCount(long userId, int itemId) {
		
	}

	public ItemBase addItem(User user, int itemId, int count, GetApproach getApproach) {
	
	}

	public List<ItemBase> addItem(User user, Collection<M2QEntry> entryList, GetApproach getApproach) {

	}

	private void throwInvalidParamsException(M2QEntry entry) {
		
	}

	public boolean decrItem(User user, int itemId, int count, DecReason decReason) {
		
	}

	public boolean decrItem(User user, Collection<M2QEntry> entryList, DecReason decReason) {
		
		
	}

	public void replaceItem(User user, ItemBase itemBase) {
		
	}

	private void replaceItem(User user, Collection<ItemBase> itemBaseList) {
		
	}

	private void pushChange(User user, Collection<ItemBase> itemBaseList) {
		
	}

	public List<UserItem> changeToUserItem(Collection<ItemBase> itemBaseList) {
		synchronized (this) {
			synchronized (itemBaseList) {
				
				}			
				return userItemList;				
			}
		}
	}

	public short useTool(User user, List<M2QEntry> m2qList, long targetId) {
		
	}

	public boolean checkEnough(User user, int itemId, int count) {
		
	}

	public boolean checkEnough(User user, Collection<M2QEntry> entryList) {
		
	}
}

**Comment by jbachorik** [comment]
Can you, please, try with #341 fix applied? I discovered another corner case in stackframe map generation and fixed that - might fix also your issue, with some luck.

**Comment by jbachorik** [comment]
Ping. Any chance to test this fix to see whether the problem goes away?

**Comment by moooonk** [comment]
Unfortunately,I donwload new btrace-bin-1.3.11 release and test.But this bug still here.

**Comment by jbachorik** [comment]
Could you try a custom built BTrace containing commit #527d86f265a0b534791309b42303879aa44da7ae ?
I added more debug info there to figure out what is throwing the stack tracing logic off.

**Comment by moooonk** [comment]
log here:
***
btrace WARNING: Unknown slot type: -2
***
***
btrace WARNING: Unknown slot type: -2
***
***
***

**Comment by jbachorik** [comment]
Any chance of sharing the compiled version of that class? I can sign whatever non-disclosure agreement if necessary and you can send it directly to my email. 
Without that, I am afraid, I won't be able to solve this problem - there seems to be some peculiarity in the stackframe maps in that class and it is throwing off the algorithm used to recompute them in instrumented methods.

**Comment by jbachorik** [comment]
Hi, I addressed this issue in `develop` branch. Can you, please, verify?
