### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by caim2015** [btraceio/btrace#343]
Hello,I want to trace the JSF's code by the BTrace.
but,when I run my JSF webapplication,occured this：

java.lang.NoClassDefFoundError: BTraceTest
	at javax.faces.component.UIComponentBase.$btrace$BTraceTest$trace1(UIComponentBase.java)
	at javax.faces.component.UIComponentBase.getClientId(UIComponentBase.java:326)
	at com.sun.faces.renderkit.html_basic.FormRenderer.encodeBegin(FormRenderer.java:127)
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:820)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1755)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1760)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1760)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:402)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:131)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:410)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:257)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:319)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:197)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:907)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:792)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1118)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:231)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:542)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:520)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: BTraceTest not found by org.glassfish.com.sun.faces [118]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1460)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:72)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1843)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 39 more

My Btrace script code follows as：
``
import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

@BTrace
public class BTraceTest {

    @OnMethod(
            clazz = "javax.faces.component.UIComponentBase",
            method = "getClientId",
            location = @Location(Kind.RETURN)
    )
    public static void trace1(@Return String clientId) { 	
    	println("clientId=" + clientId);    	 
        jstack();       
    }
}

**Comment by caim2015** [comment]
How to solve this problem?

**Comment by jbachorik** [comment]
This is an OSGI class loader isolation issue.
Please, set `org.osgi.framework.bootdelegation` property accordingly - see eg. https://felix.apache.org/documentation/subprojects/apache-felix-framework/apache-felix-framework-configuration-properties.html of https://comm.support.ca.com/kb/configuring-the-java-agent-on-glassfish/kb000048334 for reference
