### ISSUE TITLE
AllMethod regex not working

### ISSUE THREAD

**Issue by SystemOutPrint** [btraceio/btrace#368]
```java
import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

@BTrace 
public class CountInfoMethodSampled {
   
    @OnMethod(
      clazz="/a\\.b\\..*/",  // not working
      method="/.*/"
    )
    public static void m(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        print("enter " + probeClass);
        println("." + probeMethod);
    }
}
```

```java
import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

@BTrace 
public class CountInfoMethodSampled {
   
    @OnMethod(
      clazz="/a\\.b\\.c/",  // it's working
      method="/.*/"
    )
    public static void m(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        print("enter " + probeClass);
        println("." + probeMethod);
    }
}
```

**Comment by SystemOutPrint** [comment]
```
java.lang.VerifyError
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.sun.btrace.agent.Client.retransformLoaded(Client.java:484)
        at com.sun.btrace.agent.Client.onExit(Client.java:251)
        at com.sun.btrace.agent.RemoteClient.onCommand(RemoteClient.java:142)
        at com.sun.btrace.agent.RemoteClient$1.run(RemoteClient.java:96)
        at java.lang.Thread.run(Thread.java:745)
```
