### ISSUE TITLE
onThrow.java sample not working

### ISSUE THREAD

**Issue by xd125** [btraceio/btrace#370]
tried with following code with onThrow.java:
  //test exception intercept
        try {
            throw new Exception("fa");

        }
        catch (Exception ex){
            System.out.println("eat the exception");
        }

it's not working. however if I changed the btrace 1.3.10.2 it can working properly. 

if I changed to 
    @OnMethod(clazz = "/Main/" ,method="/.*/", location = @Location(Kind.ERROR))
    public static void onError( @TargetInstance Throwable err) {
        println("error occurred");
    }

then btrace agent runtime exception occured:

java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    Main.<clinit>()V @50: lload_2
  Reason:
    Local index 2 is invalid
  Bytecode:
    0x0000000: 093f b800 a841 128e 12b9 03bd 0007 b800
    0x0000010: 94bb 0025 59b7 0026 b300 27b8 00a8 2065
    0x0000020: 3fb2 009a 3a04 1e12 b919 04b8 009e b1b8
    0x0000030: 00a8 2065 3f59 3a05 1905 b800 a4bf     
  Exception Handler Table:
    bci [0, 47] => handler: 47
  Stackmap Table:
    same_locals_1_stack_item_frame(@47,Object[#160])

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
java.lang.InternalError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at com.sun.btrace.agent.Client.retransformLoaded(Client.java:484)
	at com.sun.btrace.agent.Client.onExit(Client.java:251)
	at com.sun.btrace.agent.FileClient.onCommand(FileClient.java:83)
	at com.sun.btrace.BTraceRuntime$ConsumerWrapper.accept(BTraceRuntime.java:174)
	at com.sun.btrace.BTraceRuntime$ConsumerWrapper.accept(BTraceRuntime.java:162)
	at com.sun.btrace.org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:674)
	at com.sun.btrace.BTraceRuntime$4.run(BTraceRuntime.java:442)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jbachorik** [comment]
I checked `@OnThrow` against the current code (develop branch) and it works as expected.
The `@OnError` case as well - it is related to #333 

Can you, possibly, test against a custom build from develop branch?

**Comment by jbachorik** [comment]
Closing. Please, reopen if still reproducible,
