### ISSUE TITLE
tracing using compiled script may not work 

### ISSUE THREAD

**Issue by cless91** [btraceio/btrace#381]
Hello, 

I just downloaded btrace 1.3.11.3, it works fine with .java scripts but doesn't seem to work with compiled scripts.

Here is the script : 

```java
import com.sun.btrace.annotations.*;
import com.sun.btrace.BTraceUtils;

@BTrace
public class HelloWorld {
  @OnMethod(clazz = "java.io.File", method = "<init>")
  public static void onNewFileCreated(String fileName) {
    BTraceUtils.println("New file is being created");
    BTraceUtils.println(fileName);
  }
}
```

Here is the code i try to instrument :

```java
package main;

import org.apache.commons.io.FileUtils;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class App {
  public static void main(String... args) {
    while (true) {
      String message = "coucou";
      System.out.println(message);
      File file = new File("toto.txt");
      try {
        FileUtils.write(file, message + "\n", StandardCharsets.UTF_8, true);
        Thread.sleep(3000);
      } catch (IOException | InterruptedException e1) {
        e1.printStackTrace();
      }
    }
  }
}
```

it works just fine when i use btrace with the java script, here are some log excerpt : 
```
C:\Users\me\workspace\btrace_tutorial
λ jps
26688
18884 Jps
25460 RemoteMavenServer
26888 GradleDaemon
15100 Launcher
27724 jar


C:\Users\me\workspace\btrace_tutorial
λ btrace 27724 HelloWorld.java
New file is being created
toto.txt
New file is being created
toto.txt
New file is being created
toto.txt
New file is being created
```

then when i try to do the same with the compiled script : 
```
C:\Users\me\workspace\btrace_tutorial
λ btrace 27724 HelloWorld.class
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 26988
        at com.sun.btrace.org.objectweb.asm.ClassReader.readClass(Unknown Source)
        at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sun.btrace.client.Client.getDTraceSource(Client.java:579)
        at com.sun.btrace.client.Client.submitDTrace(Client.java:554)
        at com.sun.btrace.client.Client.submit(Client.java:366)
        at com.sun.btrace.client.Main.main(Main.java:206)
Exception in thread "Thread-0" java.lang.IllegalStateException
        at com.sun.btrace.client.Client.send(Client.java:502)
        at com.sun.btrace.client.Client.sendExit(Client.java:436)
        at com.sun.btrace.client.Main$2.run(Main.java:239)
        at java.lang.Thread.run(Thread.java:748)
```

then i try launching the jar with btracer and the compiled script, but nothing happens : 
```
C:\Users\me\workspace\btrace_tutorial
λ btracer ./HelloWorld.class -jar myApp-1.0-SNAPSHOT-jar-with-dependencies.jar
coucou
coucou
coucou
coucou
coucou
coucou
```

And here with `-javaagent` and the debug mode : 
```
C:\Users\me\workspace\btrace_tutorial
λ java -javaagent:btrace-agent.jar=debug,script=HelloWorld.class,stdout=true -jar myApp-1.0-SNAPSHOT-jar-with-dependencies.jar
btrace DEBUG: debugMode is true
btrace DEBUG: stdout is true
btrace DEBUG: initial script is HelloWorld.class
btrace DEBUG: loading BTrace class
### BTrace Log: 18/04/19 23:20

btrace DEBUG: loaded 'HelloWorld' successfully
btrace DEBUG: creating BTraceRuntime instance for HelloWorld
btrace DEBUG: created BTraceRuntime instance for HelloWorld
btrace DEBUG: sending Okay command
btrace DEBUG: client HelloWorld: got com.sun.btrace.comm.OkayCommand@87aac27
btrace DEBUG: about to defineClass HelloWorld
btrace DEBUG: defineClass succeeded for HelloWorld
btrace DEBUG: new Client created com.sun.btrace.agent.FileClient@2dd11c1a
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
btrace DEBUG: candidate class java.io.File added
btrace DEBUG: client HelloWorld: got com.sun.btrace.comm.RetransformationStartNotification@4eed5683
btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
btrace DEBUG: Attempting to retransform class: java.io.File
btrace DEBUG: noServer is true, server not started
btrace DEBUG: Agent init took: 575309300ns
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleImpl
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleImpl$1
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleImpl$2
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleImpl$3
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleImpl$4
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MemberName$Factory
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleStatics
btrace DEBUG: skipping transform for BTrace class java/lang/invoke/MethodHandleStatics$1
btrace DEBUG: skipping transform for BTrace class java/lang/StringCoding$StringEncoder
coucou
btrace DEBUG: client HelloWorld: got com.sun.btrace.comm.OkayCommand@4089c68e
coucou
coucou
coucou
coucou
coucou
coucou
coucou
btrace DEBUG: client HelloWorld: got com.sun.btrace.comm.ExitCommand@4e4e30ef
btrace DEBUG: onExit:
btrace DEBUG: cleaning up transformers
btrace DEBUG: onExit: removing transformer for HelloWorld
btrace DEBUG: removing instrumentation
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
btrace DEBUG: candidate class java.io.File added
btrace DEBUG: client HelloWorld: got com.sun.btrace.comm.RetransformationStartNotification@408c1b5b
btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
btrace DEBUG: Attempting to retransform class: java.io.File
btrace DEBUG: closing all I/O
```

Thank you, even without btracec, the ability to attach and modify a running JVM is awesome enough, although it would be even better with the ability to do all that on startup.

**Comment by jbachorik** [comment]
Thanks for the report. I will take a look.
Are you, by any chance, using compiled probes from an older version? That might explain the problem - it would still need to be fixed but at least it would be fully understood. 
Currently, I am using `btracec` compiled probes with startup agent without any problems - but I am compiling with the latest BTrace.

**Comment by haohaoxuexi** [comment]
Hi, I encounter the same problem as I try to test the provided example FileTracker (that is, btrace-bin-1.3.11.3/samples/FileTracker.java). 

Here is my code line:
`...
// try to intercept the entry & return of the constructor of java.io.FileInputStream 
// as btrace-bin-1.3.11.3/samples/FileTracker.java describes
InputStream is = new FileInputStream(new File("123.txt"));
...
`

As I use btracec compiled FileTracker.class with -javaagent:<dirX>/btrace-agent.jar=script=<dirY>/FileTracker.class, it fails to intercept the constructor of java.io.FileInputStream & java.io.FileOutputStream at the startup of my code. But, when I use btrace <pid> FileTracker.java, it works fine. 

Besides, it can also intercept the constructor of a third-party's class at the startup. It seems that BTrace has some problem with intercepting JDK's class at startup.

Anybody knows why?

**Comment by jbachorik** [comment]
There seems to be a race between registering the class transformer and the class retransformation process. I am looking into it now.

**Comment by jbachorik** [comment]
Fixed in `develop` branch.
