### ISSUE TITLE
btrace WARNING: java.lang.ArrayIndexOutOfBoundsException: 11818

### ISSUE THREAD

**Issue by hehondou** [btraceio/btrace#387]
Using BTrace v1.3.11.3

btrace INFO: Redirecting output to trace.txt java.lang.ArrayIndexOutOfBoundsException: 11818 at com.sun.btrace.org.objectweb.asm.ClassReader.readClass(Unknown Source) at com.sun.btrace.runtime.BTraceClassReader.readClassSupers(BTraceClassReader.java:126) at com.sun.btrace.runtime.ClassInfo.loadExternalClass(ClassInfo.java:269) at com.sun.btrace.runtime.ClassInfo.<init>(ClassInfo.java:215) at com.sun.btrace.runtime.ClassCache.get(ClassCache.java:70) at com.sun.btrace.runtime.ClassCache.get(ClassCache.java:62) at com.sun.btrace.runtime.ClassCache.get(ClassCache.java:51) at com.sun.btrace.agent.Client.retransformLoaded(Client.java:461) at com.sun.btrace.agent.Main$3.run(Main.java:693) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by jbachorik** [comment]
Can you provide more details?
What kind of application? Are there any other code instrumentors enabled?
This exception is coming from ASM and would indicate that an incorrectly formed class data is parsed.

**Comment by beijibing** [comment]
v.1.3.11.3/v1.3.10
openjdk version "1.8.0_202"
my operation:
    btracec A.java
    btrace A.class

then get the following error:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 26721
	at com.sun.btrace.org.objectweb.asm.ClassReader.readClass(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.client.Client.getDTraceSource(Client.java:568)
	at com.sun.btrace.client.Client.submitDTrace(Client.java:543)
	at com.sun.btrace.client.Client.submit(Client.java:355)
	at com.sun.btrace.client.Main.main(Main.java:199)
Exception in thread "Thread-0" java.lang.IllegalStateException
	at com.sun.btrace.client.Client.send(Client.java:491)
	at com.sun.btrace.client.Client.sendExit(Client.java:425)
	at com.sun.btrace.client.Main$2.run(Main.java:233)
	at java.lang.Thread.run(Thread.java:748)

**Comment by olotenko** [comment]
Possibly related to https://gitlab.ow2.org/asm/asm/issues/317877 - also ArrayIndexOutOfBoundsException on ASM 5.2, but not reproducible on later versions.

**Comment by olotenko** [comment]
A bit more detail from my experiments: in my environment the error is related to the `btrace` "script" being available on classpath. When I moved it to a different location, `btrace` agent does not receive the "script" class name as one of the "loaded" classes, so parsing does not happen.

It may be useful to skip class parsing, if the magic can be seen to be `btrace`'s "script" class.
