### ISSUE TITLE
Btrace 2.0 get an error on mac

### ISSUE THREAD

**Issue by yzun** [btraceio/btrace#411]
I set JAVA_HOME and BTRACE_HOME, when i use btrace an btracec ,i get an error :
btrace INFO: "org.openjdk.btrace.core.cmdQueueLimit" not provided. Using the default cmd queue limit of 100
btrace INFO: Can not load runtime factory: org.openjdk.btrace.runtime.BTraceRuntimeImpl_9$Factory
btrace INFO: Can not load runtime factory: org.openjdk.btrace.runtime.BTraceRuntimeImpl_11$Factory
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/util/TaskListener
	at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:70)
	at org.openjdk.btrace.compiler.Compiler.main(Compiler.java:170)
Caused by: java.lang.ClassNotFoundException: com.sun.source.util.TaskListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

so, i check the btracec file, i found it can not get the ${TOOLS_JAR}

**Comment by jbachorik** [comment]
Please, add the following info:

- BTrace version
- Java version
- path of Java installation (eg. JAVA_HOME)

**Comment by ShiyiKong** [comment]
I have met the first three information, are they show because that I didn`t install Java_9 & Java_11?
```
btrace INFO: "org.openjdk.btrace.core.cmdQueueLimit" not provided. Using the default cmd queue limit of 100
btrace INFO: Can not load runtime factory: org.openjdk.btrace.runtime.BTraceRuntimeImpl_9$Factory
btrace INFO: Can not load runtime factory: org.openjdk.btrace.runtime.BTraceRuntimeImpl_11$Factory
```

**Comment by jbachorik** [comment]
Can you do `java -version`?

**Comment by jbachorik** [comment]
This looks very much like missing tools.jar on classpath - that jar contains the class which is reported as missing.
I improved the the TOOLS_JAR detection in the develop branch to correctly deal with pre-jigsaw as well as the current JDKs.
Can you give it a try using the build from the develop branch?
