### ISSUE TITLE
Btrace 2.0 giving me error, 

### ISSUE THREAD

**Issue by mjose007** [btraceio/btrace#415]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/util/TaskListener
	at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:70)
	at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:74)
	at org.openjdk.btrace.client.Client.compile(Client.java:204)
	at org.openjdk.btrace.client.Client.compile(Client.java:187)
	at org.openjdk.btrace.client.Main.main(Main.java:195)
Caused by: java.lang.ClassNotFoundException: com.sun.source.util.TaskListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 5 more
```

**Comment by ShiyiKong** [comment]
in Btrace 2.0, is the problem that the package turn to `org.openjdk.btrace.*` not `com.sun.btrace.*`?

**Comment by jbachorik** [comment]
No, this is a problem with (missing) tools.jar. There are differences between platforms and even java versions about where the classes from `com.sun.source.util` package may be found.
Can you paste here the output of `java -version` and also make sure that the application you are trying to trace is using the same Java as what you get when you run `java -version` from command line?

**Comment by DoubleQueens** [comment]
@jbachorik  I encountered the same error. My output of `java -version` is as follow:
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
I am sure that my java application using the same Java `java version "1.8.0_221"` with the command line Java version

**Comment by GracefulAncestralCode** [comment]
I had the same problem with Linux OS.And then I found that I could fix the problem by modifying the shell script.Modify the btrace script in the bin directory:
![Uploading 7231c12db2cc27c1d9ff8694f867478.png…]()

After modification, you can get the TOOLS_JAR!

**Comment by jbachorik** [comment]
Improved the the TOOLS_JAR detection in the develop branch to correctly deal with pre-jigsaw as well as the current JDKs.
Can you give it a try using the build from the develop branch?
