### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.btrace.core.Messages

### ISSUE THREAD

**Issue by tmacjx** [btraceio/btrace#435]
![image](https://user-images.githubusercontent.com/11555807/103747757-170f3880-503e-11eb-9dd9-5699e3b4aeca.png)

BTrace v.2.0.3 (825719b6633988cb0e867d895b8e062e5e9e1ff7)

what's wrong? Thanks!

**Comment by tmacjx** [comment]
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.openjdk.btrace.core.messages, locale zh_CN

**Comment by quanchangnai** [comment]
Attaching BTrace to PID: 2734257
! ERROR
java.lang.ExceptionInInitializerError
	at org.openjdk.btrace.instr.Verifier.reportError(Verifier.java:65)
	at org.openjdk.btrace.instr.BTraceMethodNode.verifySpecialParameters(BTraceMethodNode.java:412)
	at org.openjdk.btrace.instr.BTraceMethodNode.visitEnd(BTraceMethodNode.java:74)
	at org.openjdk.btrace.libs.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:782)
	at org.openjdk.btrace.instr.MethodVerifier.visitEnd(MethodVerifier.java:104)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1492)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.openjdk.btrace.instr.BTraceProbeNode.initialize(BTraceProbeNode.java:415)
	at org.openjdk.btrace.instr.BTraceProbeNode.initialize(BTraceProbeNode.java:402)
	at org.openjdk.btrace.instr.BTraceProbeNode.<init>(BTraceProbeNode.java:84)
	at org.openjdk.btrace.instr.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:111)
	at org.openjdk.btrace.agent.Client.load(Client.java:460)
	at org.openjdk.btrace.agent.Client.loadClass(Client.java:313)
	at org.openjdk.btrace.agent.Client.loadClass(Client.java:305)
	at org.openjdk.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
	at org.openjdk.btrace.agent.Main.startServer(Main.java:847)
	at org.openjdk.btrace.agent.Main.access$000(Main.java:93)
	at org.openjdk.btrace.agent.Main$2.run(Main.java:162)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.openjdk.btrace.core.messages, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
	at org.openjdk.btrace.core.Messages.<clinit>(Messages.java:37)
	... 20 more

**Comment by quanchangnai** [comment]
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.openjdk.btrace.core.messages, locale en_US

**Comment by jbachorik** [comment]
@quanchangnai Can you check with 2.1.0? There was an error bundling the messages.properties in 2.0.3

**Comment by quanchangnai** [comment]
> @quanchangnai Can you check with 2.1.0? There was an error bundling the messages.properties in 2.0.3

 17 days ago,2.0.3

**Comment by quanchangnai** [comment]
@jbachorik 
17 days ago,2.0.3

**Comment by jbachorik** [comment]
> 17 days ago,2.0.3
?
I know you used 2.0.3 that time. Can you try 2.1.0 which definitely was not released 17 days ago?

I double checked error reporting in 2.1.0 and it is working fine for me. If the problem persists can you attach the BTrace probe source triggering this error?

**Comment by quanchangnai** [comment]
> > 17 days ago,2.0.3
> 
> ?
> I know you used 2.0.3 that time. Can you try 2.1.0 which definitely was not released 17 days ago?
> 
> I double checked error reporting in 2.1.0 and it is working fine for me. If the problem persists can you attach the BTrace probe source triggering this error?

import org.openjdk.btrace.core.types.AnyType;
import org.openjdk.btrace.core.annotations.*;
import org.openjdk.btrace.core.annotations.OnMethod;

import static org.openjdk.btrace.core.BTraceUtils.*;

@BTrace
public class HelloWorld {
    @OnMethod(
            clazz = "gs.activity.ActivityModule",
            method = "getActivityList",
            location = @Location(value = Kind.LINE, line = -1)
    )
    public static void process(@ProbeClassName String className, @ProbeMethodName String methodName, @Duration long time, AnyType[] args) {
        println("className:" + className);
        println("methodName:" + methodName);
        printArray(args);
        println("time:" + str(time));
    }
}



root@n225-098-193:~/btrace/bin# ./btrace 3612291 HelloWorld.java 
Attaching BTrace to PID: 3612291
! ERROR
java.lang.ExceptionInInitializerError
	at org.openjdk.btrace.instr.Verifier.reportError(Verifier.java:65)
	at org.openjdk.btrace.instr.BTraceMethodNode.verifySpecialParameters(BTraceMethodNode.java:412)
	at org.openjdk.btrace.instr.BTraceMethodNode.visitEnd(BTraceMethodNode.java:74)
	at org.openjdk.btrace.libs.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:782)
	at org.openjdk.btrace.instr.MethodVerifier.visitEnd(MethodVerifier.java:104)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1492)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.openjdk.btrace.instr.BTraceProbeNode.initialize(BTraceProbeNode.java:415)
	at org.openjdk.btrace.instr.BTraceProbeNode.initialize(BTraceProbeNode.java:402)
	at org.openjdk.btrace.instr.BTraceProbeNode.<init>(BTraceProbeNode.java:84)
	at org.openjdk.btrace.instr.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:111)
	at org.openjdk.btrace.agent.Client.load(Client.java:460)
	at org.openjdk.btrace.agent.Client.loadClass(Client.java:313)
	at org.openjdk.btrace.agent.Client.loadClass(Client.java:305)
	at org.openjdk.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
	at org.openjdk.btrace.agent.Main.startServer(Main.java:847)
	at org.openjdk.btrace.agent.Main.access$000(Main.java:93)
	at org.openjdk.btrace.agent.Main$2.run(Main.java:162)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.openjdk.btrace.core.messages, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
	at org.openjdk.btrace.core.Messages.<clinit>(Messages.java:37)
	... 20 more

**Comment by jbachorik** [comment]
This will be resolved together with #455
