### ISSUE TITLE
ExceptionInInitializerError from NullPointerException in btrace.core.Messages.<clinit>

### ISSUE THREAD

**Issue by lacinoire** [btraceio/btrace#455]
Hey jbachorik 😊

I'm attempting to run btrace on a simple JUnit 5 examle and get the following error:
```
## BTrace Log: 17.03.21, 16:02

btrace DEBUG: BTrace runtime implementation org.openjdk.btrace.runtime.BTraceRuntimeImpl_11$Factory is loaded
btrace DEBUG: BTraceRuntime loaded: true
btrace DEBUG: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at org.openjdk.btrace.instr.Verifier.reportError(Verifier.java:60)
	at org.openjdk.btrace.instr.BTraceProbePersisted$2$1.visitMethodInsn(BTraceProbePersisted.java:734)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2419)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1488)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
	at org.openjdk.btrace.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.openjdk.btrace.instr.BTraceProbePersisted.verifyBytecode(BTraceProbePersisted.java:587)
	at org.openjdk.btrace.instr.BTraceProbePersisted.isVerified(BTraceProbePersisted.java:457)
	at org.openjdk.btrace.agent.Client.load(Client.java:482)
	at org.openjdk.btrace.agent.Client.loadClass(Client.java:331)
	at org.openjdk.btrace.agent.FileClient.init(FileClient.java:84)
	at org.openjdk.btrace.agent.FileClient.<init>(FileClient.java:60)
	at org.openjdk.btrace.agent.Main.loadBTraceScript(Main.java:804)
	at org.openjdk.btrace.agent.Main.startScripts(Main.java:322)
	at org.openjdk.btrace.agent.Main.main(Main.java:148)
	at org.openjdk.btrace.agent.Main.premain(Main.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NullPointerException
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1281)
	at org.openjdk.btrace.core.Messages.<clinit>(Messages.java:37)
	... 22 more
```

This is my trace script:
```
import org.openjdk.btrace.core.annotations.*;
import static org.openjdk.btrace.core.BTraceUtils.*;

/**
 * This script traces method entry
 */
@BTrace public class AllMethods {
    // @OnMethod(
    //     clazz="/introclassJava.*/",
    //     method="/.*/"
    // )
    @OnExit
    public static void m(int code) {//(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        // print(Strings.strcat("entered ", probeClass));
        // println(Strings.strcat(".", probeMethod));
        println("BTrace program exits!");
    }
}
```
If I comment out the annotations above the method (@OnMethod or @OnExit), the error does not occur. I've tried with multiple different annotations.

-----
btrace version: BTrace v.2.1.0 (0275890d640f1284c231a01a5b516b75701c5ad4)
java --version:
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)

I get the error both when executing with `btracer` and trough the java agent.
`btrace/bin/btracer -v --stdout -o btrace_traces/simpletrace.btrace AllMethods.class -cp .:target/classes:target/test-classes:junit-jupiter-api-5.7.1.jar:junit-jupiter-engine-5.7.1.jar:junit-platform-commons-1.7.1.jar:junit-platform-launcher-1.7.1.jar:junit-platform-engine-1.7.1.jar SingleJUnitTestRunner 'introclassJava.Syllables_WhiteboxTest#test9'`

-----

Could you give me a pointer on what might be going wrong?

**Comment by jbachorik** [comment]
This is related to #435 

The gist of the problem is that the `Messages` class is loaded by bootstrap classloader from a jar added to bootstrap by the agent. Apparently, the bootstrap classloader can not load resources from such jars, for whatever reason.

The fix is not to package this class to `btrace-boot.jar` but have it in `btrace-agent.jar` instead - then the `Messages` class will be loaded by the agent/system classloader and everything will be fine.
