### ISSUE TITLE
Issues with java.lang.ClassFormatError.

### ISSUE THREAD

**Issue by ksiczek** [btraceio/btrace#499]
Guys, maybe you can help me. I use btrace 2.2.0 or 2.3.0 to run a simple script tracing methods at `org.jboss.as.server.deployment.scanner.FileSystemDeploymentService`. It works pretty well on one environment but on the other one I constantly get

```
ERROR [stderr] [BTrace Command Queue Processor] java.lang.ClassFormatError
ERROR [stderr] [BTrace Command Queue Processor]  at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
ERROR [stderr] [BTrace Command Queue Processor]  at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
ERROR [stderr] [BTrace Command Queue Processor]  at org.openjdk.btrace.agent.Client.retransformLoaded(Client.java:513)
ERROR [stderr] [BTrace Command Queue Processor]  at org.openjdk.btrace.agent.Main.lambda$handleNewClient$3(Main.java:874)
ERROR [stderr] [BTrace Command Queue Processor]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ERROR [stderr] [BTrace Command Queue Processor]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ERROR [stderr] [BTrace Command Queue Processor]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ERROR [stderr] [BTrace Command Queue Processor]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ERROR [stderr] [BTrace Command Queue Processor]  at java.lang.Thread.run(Thread.java:748)
``` 
in the application's logs. The client says

```
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
btrace INFO: Attaching BTrace to PID: 8018
DEBUG: compiling ../src/main/java/de/telekom/phoenix/btrace/FileSystemDeploymentServiceTrace.java
DEBUG: compiled ../src/main/java/de/telekom/phoenix/btrace/FileSystemDeploymentServiceTrace.java
DEBUG: Boot classpath: .
DEBUG: attaching to 8018
DEBUG: checking port availability: 2020
DEBUG: attached to 8018
DEBUG: loading /atg/phoenix/btrace/2.3.0-SNAPSHOT/libs/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=/atg/moip/phxa_dev2/env/phoenix_jdk1-1.8.0_301/jre/../lib/tools.jar,probeDescPath=.
DEBUG: loaded /atg/phoenix/btrace/2.3.0-SNAPSHOT/libs/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command: []
DEBUG: entering into command loop
DEBUG: received org.openjdk.btrace.core.comm.RenameCommand@8b87145
DEBUG: received org.openjdk.btrace.core.comm.StatusCommand@6483f5ae
DEBUG: received org.openjdk.btrace.core.comm.RetransformationStartNotification@b9afc07
DEBUG: received org.openjdk.btrace.core.comm.StatusCommand@382db087
btrace INFO: Successfully started BTrace probe: ../src/main/java/de/telekom/phoenix/btrace/FileSystemDeploymentServiceTrace.java
```
and on the server side I have found
```
[stdout] (Thread-273) btrace DEBUG: client accepted Socket[addr=/127.0.0.1,port=46458,localport=2020]
[stdout] (Thread-273) btrace DEBUG: got instrument command
[stdout] (Thread-273) btrace DEBUG: loading BTrace class
[stdout] (Thread-273) btrace DEBUG: verifying BTrace class ...
[stdout] (Thread-273) btrace DEBUG: BTrace class org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2 verified
[stdout] (Thread-273) btrace DEBUG: preprocessing BTrace class org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2 ...
[stdout] (Thread-273) btrace DEBUG: ... preprocessed
[stdout] (Thread-273) btrace DEBUG: loaded 'org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2' successfully
[stdout] (Thread-273) btrace DEBUG: class renamed to org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: client org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2: got org.openjdk.btrace.core.comm.RenameCommand@36c21393
[stdout] (Thread-273) btrace DEBUG: creating BTraceRuntime instance for org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: created BTraceRuntime instance for org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: sending Okay command
[stdout] (Thread-273) btrace DEBUG: client org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2: got org.openjdk.btrace.core.comm.StatusCommand@4631ad79
[stdout] (Thread-273) btrace DEBUG: about to defineClass org/openjdk/btrace/runtime/auxiliary/FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: init: clazz = null, cl = class org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: init: timerHandlers = null
[stdout] (Thread-273) btrace DEBUG: defineClass succeeded for org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2
[stdout] (Thread-273) btrace DEBUG: starting client command handler thread
[stdout] (BTrace Command Queue Processor) btrace DEBUG: new Client created BTrace Client: 0439becc-b1f1-4da0-a31e-a94dda88ad7e[org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2]
[stdout] (BTrace Command Queue Processor) btrace DEBUG: retransforming loaded classes
[stdout] (BTrace Command Queue Processor) btrace DEBUG: filtering loaded classes
[stdout] (BTrace Command Queue Processor) btrace DEBUG: candidate class org.jboss.as.server.deployment.scanner.FileSystemDeploymentService added
[stdout] (BTrace Command Queue Processor) btrace DEBUG: client org.openjdk.btrace.runtime.auxiliary.FileSystemDeploymentServiceTrace$2: got org.openjdk.btrace.core.comm.RetransformationStartNotification@38df5ec
[stdout] (BTrace Command Queue Processor) btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
[stdout] (BTrace Command Queue Processor) btrace DEBUG: Attempting to retransform class: org.jboss.as.server.deployment.scanner.FileSystemDeploymentService
[stdout] (BTrace Command Queue Processor) btrace DEBUG: transformed class org.jboss.as.server.deployment.scanner.FileSystemDeploymentService
[stdout] (Thread-273) btrace DEBUG: waiting for clients
```

Do you have any ideas about what might be wrong? I changed the `org.jboss.as.server.deployment.scanner.FileSystemDeploymentService` to a class from my application and probes started working so it seems that it might be related to the JBoss modules but I am not sure about that. Any help would be appreciated.

**Comment by jbachorik** [comment]
Can you run BTrace with `-d <output_dir>` argument to dump the instrumented classes and then eg. attach the one failing the verification here?

**Comment by ksiczek** [comment]
Here you go @jbachorik - [classverificationerr.zip](https://github.com/btraceio/btrace/files/7276826/classverificationerr.zip)

I instrument only `org.jboss.as.server.deployment.scanner.FileSystemDeploymentService` but I attached the whole folder.

**Comment by jbachorik** [comment]
After another few hours I really can not find anything wrong with the instrumented class.
My guess is that there is something going on between BTrace and the JBoss module system - I tried fiddling around with the `JBOSS_MODULES_SYSTEM_PKGS` env variable which seems to be the way to let wildfly/jboss access the byteman agent but that didn't help either :(

I am afraid that this will require someone knowledgeable of the inner workings of the jboss module system - not sure there will be a lot of volunteers, given that they have their own byteman tool which is very similar to BTrace in what it does and how it does it.
