### ISSUE TITLE
When using btrace to log return value breaks the java application

### ISSUE THREAD

**Issue by davidgargti20** [btraceio/btrace#549]

**Comment by jbachorik** [comment]
Can you provide more details?
Error log and the output in verbose mode would be a good starting point.

**Comment by davidgargti20** [comment]
org.springframework.cglib.core.CodeGenerationException: java.lang.VerifyError-->Inconsistent stackmap frames at branch target 50
Exception Details:
  Location:
    org/springframework/samples/petclinic/PetClinicApplication$$EnhancerBySpringCGLIB$$51762d53.CGLIB$findMethodProxy(Lorg/springframework/cglib/core/Signature;)Lorg/springframework/cglib/proxy/MethodProxy; @50: pop
  Reason:
    Type top (current frame, locals[1]) is not assignable to 'org/springframework/cglib/proxy/MethodProxy' (stack map, locals[1])
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/springframework/cglib/core/Signature' }
    stack: { 'java/lang/String', integer }
  Stackmap Frame:
    bci: @50
    flags: { }
    locals: { 'org/springframework/cglib/core/Signature', 'org/springframework/cglib/proxy/MethodProxy' }
    stack: { 'java/lang/String' }
  Bytecode:
    0000000: 2ab6 0043 59b6 0047 aa00 0000 0000 002a
    0000010: 7ce8 da84 7ce8 da84 0000 0014 1249 b600
    0000020: 4d99 0012 b200 3759 4c12 ad2b ba00 a700
    0000030: 00b0 5701 594d 12ad 2cba 00a7 0000 b0  
  Stackmap Table:
    same_locals_1_stack_item_frame(@28,Object[#79])
    full_frame(@50,{Object[#175],Object[#106]},{Object[#79]})
    chop_frame(@51,1)

        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:512) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-5.3.20.jar!/:5.3.20]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:572) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:419) ~[spring-core-5.3.20.jar!/:5.3.20]
        at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:137) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:447) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:268) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:325) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:147) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.20.jar!/:5.3.20]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.0.jar!/:2.7.0]
        at org.springframework.samples.petclinic.PetClinicApplication.main(PetClinicApplication.java:32) ~[classes!/:2.7.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[spring-petclinic-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[spring-petclinic-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[spring-petclinic-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[spring-petclinic-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 50
Exception Details:
  Location:
    org/springframework/samples/petclinic/PetClinicApplication$$EnhancerBySpringCGLIB$$51762d53.CGLIB$findMethodProxy(Lorg/springframework/cglib/core/Signature;)Lorg/springframework/cglib/proxy/MethodProxy; @50: pop
  Reason:
    Type top (current frame, locals[1]) is not assignable to 'org/springframework/cglib/proxy/MethodProxy' (stack map, locals[1])
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/springframework/cglib/core/Signature' }
    stack: { 'java/lang/String', integer }
  Stackmap Frame:
    bci: @50
    flags: { }
    locals: { 'org/springframework/cglib/core/Signature', 'org/springframework/cglib/proxy/MethodProxy' }
    stack: { 'java/lang/String' }
  Bytecode:
    0000000: 2ab6 0043 59b6 0047 aa00 0000 0000 002a
    0000010: 7ce8 da84 7ce8 da84 0000 0014 1249 b600
    0000020: 4d99 0012 b200 3759 4c12 ad2b ba00 a700
    0000030: 00b0 5701 594d 12ad 2cba 00a7 0000 b0  
  Stackmap Table:
    same_locals_1_stack_item_frame(@28,Object[#79])
    full_frame(@50,{Object[#175],Object[#106]},{Object[#79]})
    chop_frame(@51,1)

        at java.base/java.lang.ClassLoader.defineClass0(Native Method) ~[na:na]
        at java.base/java.lang.System$2.defineClass(System.java:2346) ~[na:na]
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2432) ~[na:na]
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2409) ~[na:na]
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1835) ~[na:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:507) ~[spring-core-5.3.20.jar!/:5.3.20]
        ... 33 common frames omitted

**Comment by davidgargti20** [comment]
I tried on couple projects on other one no error shows it simply stops

**Comment by jbachorik** [comment]
Thanks for the logs. I will definitely take a look. 

This looks like BTrace instrumentation is confusing the spring instrumentation - I guess all the failures are for spring apps, right?

**Comment by davidgargti20** [comment]
I think the issue is of bytecode verification

**Comment by jbachorik** [comment]
Yes, definitely. But I haven't seen this problem outside of spring - there are several tests for the return value capture and the instrumented code is validated successfully.

The cglib is also modifying bytecode. Obviously, two parties are doing the modifications and the result is invalid.

**Comment by jbachorik** [comment]
Could you try and capture the instrumented classes by using `dumpClasses` and `dumpDir` agent arguments (https://github.com/btraceio/btrace/wiki)? And then attach the classes here?
