### ISSUE TITLE
Does the BTrace agent support java 17? 

### ISSUE THREAD

**Issue by joachimhs** [btraceio/btrace#574]
Hello, 

I am getting the following error when trying to run BTrace through the -javaagent command on my Java 17 application. Does BTrace support JDK17, or do I need to downgrade to 11? 

`### BTrace Log: 09.09.2022, 15:18

! ERROR
java.lang.IllegalAccessError: class org.openjdk.btrace.core.BTraceRuntime (in unnamed module @0x64b8f8f4) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x64b8f8f4
	at org.openjdk.btrace.core.BTraceRuntime.property(BTraceRuntime.java:806)
	at org.openjdk.btrace.core.BTraceUtils$Sys$Env.property(BTraceUtils.java:5926)
	at org.openjdk.btrace.core.BTraceUtils.property(BTraceUtils.java:2455)
	at org.openjdk.btrace.runtime.auxiliary.TraceMem.printMem(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openjdk.btrace.runtime.BTraceRuntimeImplBase$2.run(BTraceRuntimeImplBase.java:1038)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
`

**Comment by jbachorik** [comment]
BTrace itself does support Java 17.
However, it seems like you found a missing piece where the code used to read a property is relying on an internal class from from a package for which the module definition hasn't been patched yet.
